CREATE USER benchmarkdbuser IDENTIFIED BY benchmarkdbpass
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO benchmarkdbuser;
GRANT RESOURCE TO benchmarkdbuser;
ALTER USER benchmarkdbuser DEFAULT ROLE CONNECT, RESOURCE;
GRANT CREATE SESSION TO benchmarkdbuser WITH ADMIN OPTION;
